name: Build & Deploy Java Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: check maven wrapper version
        run: ./mvnw --version

      - name: create toolchains.xml
        run: echo '<?xml version="1.0" encoding="UTF-8"?><toolchains><toolchain><type>jdk</type><provides><version>1.8</version></provides><configuration><jdkHome>${env.JAVA_HOME}</jdkHome></configuration></toolchain></toolchains>' > ~/.m2/toolchains.xml

      - name: verify
        run: ./mvnw verify -B
