name: Build & Deploy Java Project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Check maven wrapper version
        run: ./mvnw --version

      - name: Create toolchains.xml
        run: echo '<?xml version="1.0" encoding="UTF-8"?><toolchains><toolchain><type>jdk</type><provides><version>1.8</version></provides><configuration><jdkHome>${env.JAVA_HOME}</jdkHome></configuration></toolchain></toolchains>' > ~/.m2/toolchains.xml

      - name: Configure your Git username/email
        run: |
          git config --global user.email "commits-noreply@github.com"
          git config --global user.name "GitHub Actions"

      - name: Release & Deploy to GitHub Packages
        run: ./mvnw release:prepare release:perform -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
